"""Initial create 

Revision ID: 3c6df1d9fa02
Revises: 
Create Date: 2022-05-26 05:18:41.828696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c6df1d9fa02'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('given_id', sa.Integer(), nullable=True),
    sa.Column('circuit_ref', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('alt', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuits_alt'), 'circuits', ['alt'], unique=False)
    op.create_index(op.f('ix_circuits_circuit_ref'), 'circuits', ['circuit_ref'], unique=True)
    op.create_index(op.f('ix_circuits_country'), 'circuits', ['country'], unique=False)
    op.create_index(op.f('ix_circuits_given_id'), 'circuits', ['given_id'], unique=True)
    op.create_index(op.f('ix_circuits_id'), 'circuits', ['id'], unique=False)
    op.create_index(op.f('ix_circuits_latitude'), 'circuits', ['latitude'], unique=False)
    op.create_index(op.f('ix_circuits_location'), 'circuits', ['location'], unique=False)
    op.create_index(op.f('ix_circuits_longitude'), 'circuits', ['longitude'], unique=False)
    op.create_index(op.f('ix_circuits_name'), 'circuits', ['name'], unique=False)
    op.create_index(op.f('ix_circuits_url'), 'circuits', ['url'], unique=False)
    op.create_table('constructors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('given_id', sa.Integer(), nullable=True),
    sa.Column('reference', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_constructors_given_id'), 'constructors', ['given_id'], unique=True)
    op.create_index(op.f('ix_constructors_id'), 'constructors', ['id'], unique=False)
    op.create_index(op.f('ix_constructors_name'), 'constructors', ['name'], unique=False)
    op.create_index(op.f('ix_constructors_nationality'), 'constructors', ['nationality'], unique=False)
    op.create_index(op.f('ix_constructors_reference'), 'constructors', ['reference'], unique=False)
    op.create_index(op.f('ix_constructors_url'), 'constructors', ['url'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('given_id', sa.Integer(), nullable=True),
    sa.Column('driver_ref', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('forename', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drivers_code'), 'drivers', ['code'], unique=False)
    op.create_index(op.f('ix_drivers_date_of_birth'), 'drivers', ['date_of_birth'], unique=False)
    op.create_index(op.f('ix_drivers_driver_ref'), 'drivers', ['driver_ref'], unique=True)
    op.create_index(op.f('ix_drivers_forename'), 'drivers', ['forename'], unique=False)
    op.create_index(op.f('ix_drivers_given_id'), 'drivers', ['given_id'], unique=True)
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_index(op.f('ix_drivers_nationality'), 'drivers', ['nationality'], unique=False)
    op.create_index(op.f('ix_drivers_number'), 'drivers', ['number'], unique=False)
    op.create_index(op.f('ix_drivers_surname'), 'drivers', ['surname'], unique=False)
    op.create_index(op.f('ix_drivers_url'), 'drivers', ['url'], unique=False)
    op.create_table('statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('given_id', sa.Integer(), nullable=True),
    sa.Column('status_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statuses_given_id'), 'statuses', ['given_id'], unique=True)
    op.create_index(op.f('ix_statuses_id'), 'statuses', ['id'], unique=False)
    op.create_index(op.f('ix_statuses_status_name'), 'statuses', ['status_name'], unique=True)
    op.create_table('races',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('given_id', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_races_date'), 'races', ['date'], unique=False)
    op.create_index(op.f('ix_races_given_id'), 'races', ['given_id'], unique=True)
    op.create_index(op.f('ix_races_id'), 'races', ['id'], unique=False)
    op.create_index(op.f('ix_races_name'), 'races', ['name'], unique=False)
    op.create_index(op.f('ix_races_round'), 'races', ['round'], unique=False)
    op.create_index(op.f('ix_races_time'), 'races', ['time'], unique=False)
    op.create_index(op.f('ix_races_url'), 'races', ['url'], unique=False)
    op.create_index(op.f('ix_races_year'), 'races', ['year'], unique=False)
    op.create_table('lap_times',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lap', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('time_str', sa.String(), nullable=False),
    sa.Column('time_milli', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lap_times_id'), 'lap_times', ['id'], unique=False)
    op.create_index(op.f('ix_lap_times_lap'), 'lap_times', ['lap'], unique=False)
    op.create_index(op.f('ix_lap_times_position'), 'lap_times', ['position'], unique=False)
    op.create_index(op.f('ix_lap_times_time_milli'), 'lap_times', ['time_milli'], unique=False)
    op.create_index(op.f('ix_lap_times_time_str'), 'lap_times', ['time_str'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('given_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('grid', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('position_text', sa.String(), nullable=False),
    sa.Column('position_order', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('laps', sa.Integer(), nullable=False),
    sa.Column('time_str', sa.String(), nullable=True),
    sa.Column('time_milli', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('fastest_lap', sa.Integer(), nullable=True),
    sa.Column('fastest_time', sa.String(), nullable=True),
    sa.Column('fastest_speed', sa.Float(), nullable=True),
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('constructor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_fastest_lap'), 'results', ['fastest_lap'], unique=False)
    op.create_index(op.f('ix_results_fastest_speed'), 'results', ['fastest_speed'], unique=False)
    op.create_index(op.f('ix_results_fastest_time'), 'results', ['fastest_time'], unique=False)
    op.create_index(op.f('ix_results_given_id'), 'results', ['given_id'], unique=True)
    op.create_index(op.f('ix_results_grid'), 'results', ['grid'], unique=False)
    op.create_index(op.f('ix_results_id'), 'results', ['id'], unique=False)
    op.create_index(op.f('ix_results_laps'), 'results', ['laps'], unique=False)
    op.create_index(op.f('ix_results_number'), 'results', ['number'], unique=False)
    op.create_index(op.f('ix_results_points'), 'results', ['points'], unique=False)
    op.create_index(op.f('ix_results_position'), 'results', ['position'], unique=False)
    op.create_index(op.f('ix_results_position_order'), 'results', ['position_order'], unique=False)
    op.create_index(op.f('ix_results_position_text'), 'results', ['position_text'], unique=False)
    op.create_index(op.f('ix_results_rank'), 'results', ['rank'], unique=False)
    op.create_index(op.f('ix_results_time_milli'), 'results', ['time_milli'], unique=False)
    op.create_index(op.f('ix_results_time_str'), 'results', ['time_str'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_time_str'), table_name='results')
    op.drop_index(op.f('ix_results_time_milli'), table_name='results')
    op.drop_index(op.f('ix_results_rank'), table_name='results')
    op.drop_index(op.f('ix_results_position_text'), table_name='results')
    op.drop_index(op.f('ix_results_position_order'), table_name='results')
    op.drop_index(op.f('ix_results_position'), table_name='results')
    op.drop_index(op.f('ix_results_points'), table_name='results')
    op.drop_index(op.f('ix_results_number'), table_name='results')
    op.drop_index(op.f('ix_results_laps'), table_name='results')
    op.drop_index(op.f('ix_results_id'), table_name='results')
    op.drop_index(op.f('ix_results_grid'), table_name='results')
    op.drop_index(op.f('ix_results_given_id'), table_name='results')
    op.drop_index(op.f('ix_results_fastest_time'), table_name='results')
    op.drop_index(op.f('ix_results_fastest_speed'), table_name='results')
    op.drop_index(op.f('ix_results_fastest_lap'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_lap_times_time_str'), table_name='lap_times')
    op.drop_index(op.f('ix_lap_times_time_milli'), table_name='lap_times')
    op.drop_index(op.f('ix_lap_times_position'), table_name='lap_times')
    op.drop_index(op.f('ix_lap_times_lap'), table_name='lap_times')
    op.drop_index(op.f('ix_lap_times_id'), table_name='lap_times')
    op.drop_table('lap_times')
    op.drop_index(op.f('ix_races_year'), table_name='races')
    op.drop_index(op.f('ix_races_url'), table_name='races')
    op.drop_index(op.f('ix_races_time'), table_name='races')
    op.drop_index(op.f('ix_races_round'), table_name='races')
    op.drop_index(op.f('ix_races_name'), table_name='races')
    op.drop_index(op.f('ix_races_id'), table_name='races')
    op.drop_index(op.f('ix_races_given_id'), table_name='races')
    op.drop_index(op.f('ix_races_date'), table_name='races')
    op.drop_table('races')
    op.drop_index(op.f('ix_statuses_status_name'), table_name='statuses')
    op.drop_index(op.f('ix_statuses_id'), table_name='statuses')
    op.drop_index(op.f('ix_statuses_given_id'), table_name='statuses')
    op.drop_table('statuses')
    op.drop_index(op.f('ix_drivers_url'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_surname'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_number'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_nationality'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_given_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_forename'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_driver_ref'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_date_of_birth'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_code'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_constructors_url'), table_name='constructors')
    op.drop_index(op.f('ix_constructors_reference'), table_name='constructors')
    op.drop_index(op.f('ix_constructors_nationality'), table_name='constructors')
    op.drop_index(op.f('ix_constructors_name'), table_name='constructors')
    op.drop_index(op.f('ix_constructors_id'), table_name='constructors')
    op.drop_index(op.f('ix_constructors_given_id'), table_name='constructors')
    op.drop_table('constructors')
    op.drop_index(op.f('ix_circuits_url'), table_name='circuits')
    op.drop_index(op.f('ix_circuits_name'), table_name='circuits')
    op.drop_index(op.f('ix_circuits_longitude'), table_name='circuits')
    op.drop_index(op.f('ix_circuits_location'), table_name='circuits')
    op.drop_index(op.f('ix_circuits_latitude'), table_name='circuits')
    op.drop_index(op.f('ix_circuits_id'), table_name='circuits')
    op.drop_index(op.f('ix_circuits_given_id'), table_name='circuits')
    op.drop_index(op.f('ix_circuits_country'), table_name='circuits')
    op.drop_index(op.f('ix_circuits_circuit_ref'), table_name='circuits')
    op.drop_index(op.f('ix_circuits_alt'), table_name='circuits')
    op.drop_table('circuits')
    # ### end Alembic commands ###
